#!/bin/bash

# ============================================
# UTLMediCore Agentic AI - Auto Setup Script
# ============================================

echo "🚀 UTLMediCore Agentic AI Setup Script"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check Python version
echo "📋 Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
REQUIRED_VERSION="3.8"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" = "$REQUIRED_VERSION" ]; then 
    echo -e "${GREEN}✅ Python $PYTHON_VERSION found${NC}"
else
    echo -e "${RED}❌ Python 3.8+ required. Found: $PYTHON_VERSION${NC}"
    exit 1
fi

# Check if Ollama is installed
echo ""
echo "📋 Checking Ollama installation..."
if command -v ollama &> /dev/null; then
    echo -e "${GREEN}✅ Ollama found${NC}"
else
    echo -e "${YELLOW}⚠️  Ollama not found. Installing...${NC}"
    echo "Please install from: https://ollama.ai"
    echo "Then run this script again."
    exit 1
fi

# Install Python dependencies
echo ""
echo "📦 Installing Python dependencies..."
pip3 install -r requirements.txt

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Python dependencies installed${NC}"
else
    echo -e "${RED}❌ Failed to install dependencies${NC}"
    exit 1
fi

# Pull Ollama models
echo ""
echo "🤖 Pulling Ollama AI models..."
echo "This may take a while (multiple GB downloads)..."

MODELS=("llama3.1:8b" "qwen2.5:7b" "deepseek-r1:8b" "meditron:7b")

for model in "${MODELS[@]}"; do
    echo ""
    echo "Pulling $model..."
    ollama pull $model
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ $model downloaded${NC}"
    else
        echo -e "${YELLOW}⚠️  Failed to download $model (optional)${NC}"
    fi
done

# Create necessary directories
echo ""
echo "📁 Creating directory structure..."
mkdir -p templates
mkdir -p static
mkdir -p logs

echo -e "${GREEN}✅ Directories created${NC}"

# MongoDB connection test
echo ""
echo "🔌 Testing MongoDB connection..."
read -p "Enter MongoDB URL (press Enter to skip): " MONGO_URL

if [ ! -z "$MONGO_URL" ]; then
    # Simple connection test using Python
    python3 << EOF
from pymongo import MongoClient
import sys

try:
    client = MongoClient("$MONGO_URL", serverSelectionTimeoutMS=5000)
    client.admin.command('ismaster')
    print("✅ MongoDB connection successful!")
    sys.exit(0)
except Exception as e:
    print(f"❌ MongoDB connection failed: {e}")
    sys.exit(1)
EOF
else
    echo -e "${YELLOW}⚠️  MongoDB test skipped${NC}"
fi

# Create configuration file
echo ""
echo "⚙️  Creating configuration file..."

cat > config.py << 'EOF'
# UTLMediCore Agentic AI Configuration
# Auto-generated by setup script

class Config:
    # MongoDB
    MONGO_URL = 'mongodb://utl:2041$$@218.161.3.98:27017/'
    DB_LIST = ['DCA632971FC3', '2CCF6754457F']
    COLLECTION_NAME = 'posture_data'
    
    # Flask
    SECRET_KEY = 'medicore-secret-2025-change-in-production'
    DEBUG = True
    
    # Agents
    AUTO_ANALYSIS_INTERVAL = 30  # seconds
    AUTO_ALERT_ENABLED = True
    PATTERN_DETECTION_WINDOW = 100
    
    # Thresholds
    ABNORMAL_HR_LOW = 45
    ABNORMAL_HR_HIGH = 110
    HYPOXIA_THRESHOLD = 90
    
    # Models
    MONITOR_AGENT = "ollama:llama3.1:8b"
    ANALYZER_AGENT = "ollama:qwen2.5:7b"
    ALERT_AGENT = "ollama:deepseek-r1:8b"
    PREDICTOR_AGENT = "ollama:meditron:7b"
    COORDINATOR_AGENT = "ollama:qwen2.5:7b"

# Override with environment variables if available
import os
Config.MONGO_URL = os.getenv('MONGO_URL', Config.MONGO_URL)
Config.AUTO_ANALYSIS_INTERVAL = int(os.getenv('AUTO_ANALYSIS_INTERVAL', Config.AUTO_ANALYSIS_INTERVAL))
EOF

echo -e "${GREEN}✅ Configuration file created: config.py${NC}"

# Create startup script
echo ""
echo "📝 Creating startup scripts..."

cat > start_agentic.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting UTLMediCore Agentic AI System..."
python3 agentic_medicore.py
EOF

chmod +x start_agentic.sh

cat > start_all.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting ALL UTLMediCore Services..."
echo ""

# Start Node.js dashboard (if exists)
if [ -f "server.js" ]; then
    echo "Starting IMU Dashboard (Port 3000)..."
    node server.js &
    DASHBOARD_PID=$!
fi

# Wait a bit
sleep 2

# Start Agentic AI
echo "Starting Agentic AI (Port 5000)..."
python3 agentic_medicore.py &
AGENTIC_PID=$!

echo ""
echo "✅ All services started!"
echo "IMU Dashboard: http://localhost:3000"
echo "Agentic AI: http://localhost:5000"
echo ""
echo "Press Ctrl+C to stop all services"

# Wait for Ctrl+C
trap "echo 'Stopping services...'; kill $DASHBOARD_PID $AGENTIC_PID 2>/dev/null; exit" INT
wait
EOF

chmod +x start_all.sh

echo -e "${GREEN}✅ Startup scripts created${NC}"

# Create systemd service (Linux only)
if [ -f "/etc/systemd/system" ]; then
    echo ""
    read -p "Create systemd service for auto-start? (y/n): " CREATE_SERVICE
    
    if [ "$CREATE_SERVICE" = "y" ]; then
        CURRENT_DIR=$(pwd)
        
        cat > /tmp/medicore-agentic.service << EOF
[Unit]
Description=UTLMediCore Agentic AI Service
After=network.target mongodb.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$CURRENT_DIR
ExecStart=/usr/bin/python3 $CURRENT_DIR/agentic_medicore.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
        
        sudo mv /tmp/medicore-agentic.service /etc/systemd/system/
        sudo systemctl daemon-reload
        
        echo -e "${GREEN}✅ Systemd service created${NC}"
        echo "To enable auto-start:"
        echo "  sudo systemctl enable medicore-agentic"
        echo "  sudo systemctl start medicore-agentic"
    fi
fi

# Final summary
echo ""
echo "========================================"
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "========================================"
echo ""
echo "📁 Files created:"
echo "  - config.py (Configuration)"
echo "  - start_agentic.sh (Start Agentic AI only)"
echo "  - start_all.sh (Start all services)"
echo ""
echo "🚀 Quick Start:"
echo "  1. Review config.py and update if needed"
echo "  2. Run: ./start_agentic.sh"
echo "  3. Open browser: http://localhost:5000"
echo ""
echo "📚 Documentation:"
echo "  - See AGENTIC_AI_DOCUMENTATION.md for full guide"
echo ""
echo "🔧 Troubleshooting:"
echo "  - Check logs in terminal output"
echo "  - Verify Ollama is running: ollama list"
echo "  - Test MongoDB: python3 -c 'from pymongo import MongoClient; print(MongoClient(\"YOUR_URL\").admin.command(\"ismaster\"))'"
echo ""
echo "Need help? Check the documentation!"
